import { memo, useEffect, useRef, useState } from 'react';
import { Terminal } from 'lucide-react';
import { useI18n } from '../../i18n';

/**
 * INI showcase pane with a typewriter that boots when scrolled into view.
 *
 * Why the line-by-line refactor: the previous implementation re-rendered
 * the full 16-line table on every typewriter tick (~20 ms). That made the
 * whole block flash visibly on every keystroke. Now completed lines are
 * memoized and never re-render, and only the single "active" line updates
 * during typing — same visual effect, no jitter.
 */

/**
 * Sample INI shown in the landing typewriter. Mirrors the EXACT format our
 * /output/<token> endpoint emits (see services/whitelist.ts → buildIniForServer),
 * so the preview is honest: same header, same Group= / Admin= structure,
 * same `[TAG] Username` trailing comments. Don't invent fields here that
 * aren't actually produced by the server.
 */
const INI_LINES = [
  '// Generated by SquadPermissionManager',
  '// Server: EU-WEST-01',
  '// Updated: 2026-05-16T19:42:11Z',
  '',
  'Group=Task Force Alpha:reserve',
  'Group=9th Recon Battalion:reserve',
  'Group=VIP Reserve:reserve,cameraman',
  'Group=Server Admins:reserve,cameraman,debug,kick,ban,changemap',
  '',
  'Admin=76561198042170481:Task Force Alpha // [TF-α] Wolfhound_77',
  'Admin=76561197971881107:Task Force Alpha // [TF-α] Bravo.Six',
  'Admin=76561198000122240:9th Recon Battalion // [9TH] Iceberg_M',
  'Admin=76561198214770712:9th Recon Battalion // [9TH] K-9',
  'Admin=76561198200012345:VIP Reserve // GoldDonator',
  'Admin=76561198201123456:VIP Reserve // PatreonSupporter',
  'Admin=76561198300010001:Server Admins // HeadAdmin',
];

/** Pick the colour class for a fully-rendered line. */
function lineClass(line: string): string {
  if (line.startsWith(';') || line.startsWith('//')) return 'text-surface-500 italic';
  if (line.startsWith('Group=')) return 'text-accent-400';
  if (line.startsWith('Admin=')) return 'text-emerald-300';
  return 'text-surface-300';
}

/** Split a line into [main, trailingComment] where the comment begins at `//`. */
function splitComment(line: string): [string, string | null] {
  if (line.startsWith('//') || line.startsWith(';')) return [line, null];
  const idx = line.indexOf('//');
  if (idx <= 0) return [line, null];
  return [line.slice(0, idx), line.slice(idx)];
}

/**
 * Memoized row. React skips re-rendering completed lines — only the
 * currently-typing line gets fresh props on each tick.
 */
const Row = memo(function Row({
  index,
  text,
  withCursor,
}: {
  index: number;
  text: string;
  withCursor?: boolean;
}) {
  const cls = lineClass(text);
  const [main, comment] = splitComment(text);
  return (
    <div className="flex">
      <span className="w-8 select-none text-surface-700 text-right pr-3">
        {String(index + 1).padStart(2, ' ')}
      </span>
      <span className="flex-1">
        <span className={cls}>{main || (text === '' ? ' ' : '')}</span>
        {comment !== null && (
          <span className="text-surface-500 italic">{comment}</span>
        )}
        {withCursor && <span className="spm-typewriter-cursor" />}
      </span>
    </div>
  );
});

export default function IniBlock() {
  const { t, locale } = useI18n();
  /** Index of the line currently being typed (0..INI_LINES.length).
   *  When equal to INI_LINES.length, typing is done. */
  const [lineIdx, setLineIdx] = useState(0);
  /** Substring of INI_LINES[lineIdx] typed so far. */
  const [active, setActive] = useState('');
  const [done, setDone] = useState(false);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const startedRef = useRef(false);

  // (Re)trigger the typewriter on scroll-into-view + on language change.
  useEffect(() => {
    setLineIdx(0);
    setActive('');
    setDone(false);
    startedRef.current = false;

    const el = containerRef.current;
    if (!el) return;

    const run = () => {
      if (startedRef.current) return;
      startedRef.current = true;

      let li = 0;
      let ci = 0;
      const tick = () => {
        const line = INI_LINES[li];
        if (line === undefined) {
          setDone(true);
          return;
        }
        // Empty line — instant, advance past it.
        if (line.length === 0) {
          setLineIdx(li + 1);
          setActive('');
          li += 1;
          ci = 0;
          setTimeout(tick, 30);
          return;
        }
        // Advance 1-3 chars per tick; finish if past end of this line.
        const step = 1 + Math.floor(Math.random() * 3);
        ci = Math.min(ci + step, line.length);
        setActive(line.slice(0, ci));

        if (ci >= line.length) {
          // Line completed: commit it (lineIdx moves forward).
          // Use a brief pause before the next line for natural rhythm.
          setTimeout(() => {
            li += 1;
            ci = 0;
            setLineIdx(li);
            setActive('');
            setTimeout(tick, 40);
          }, 30);
        } else {
          setTimeout(tick, 14 + Math.random() * 20);
        }
      };
      tick();
    };

    const io = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) { run(); io.disconnect(); return; }
        }
      },
      { threshold: 0.2 }
    );
    io.observe(el);

    // Above the fold? Kick off immediately.
    const r = el.getBoundingClientRect();
    if (r.top < window.innerHeight && r.bottom > 0) {
      run();
      io.disconnect();
    }

    return () => io.disconnect();
  }, [locale]);

  // Pre-render the array of rows. Completed rows take their text from
  // INI_LINES, the active row takes its text from `active`. Empty
  // placeholder rows reserve vertical space so nothing shifts when typing.
  const rows = INI_LINES.map((fullText, i) => {
    if (done) {
      return <Row key={i} index={i} text={fullText} />;
    }
    if (i < lineIdx) {
      // This line is already fully typed.
      return <Row key={i} index={i} text={fullText} />;
    }
    if (i === lineIdx) {
      // The active line — only this Row re-renders during typing.
      return <Row key={i} index={i} text={active} withCursor />;
    }
    // Not yet started — render an empty placeholder so the block keeps
    // its full height and existing rows stay in place.
    return <Row key={i} index={i} text="" />;
  });

  return (
    <div ref={containerRef}>
      {/* Tab strip */}
      <div className="flex items-center justify-between border-b border-surface-700/40 px-3 h-9">
        <div className="flex items-center gap-1">
          <div className="flex items-center gap-1.5 px-3 h-7 rounded-t-md bg-surface-950/60 border-t border-l border-r border-surface-700/40 -mb-px">
            <Terminal size={12} className="text-accent-400" />
            <span className="font-mono text-[11px] text-surface-200">Admins.cfg</span>
          </div>
          <div className="hidden sm:flex items-center gap-1.5 px-3 h-7 text-surface-500 font-mono text-[11px]">
            RemoteAdminListHosts.cfg
          </div>
        </div>
        <div className="font-mono text-[10px] tracking-wider text-surface-500">{t('landIniHeader')}</div>
      </div>

      {/* Reserve final block height up front + stable scrollbar gutter so
          the typewriter has nowhere to push the surrounding section. */}
      <pre
        className="font-mono text-[12.5px] leading-[1.65] text-surface-300 px-4 py-4 bg-surface-950/40 overflow-x-auto"
        style={{
          minHeight: `${INI_LINES.length * 12.5 * 1.65 + 32}px`,
          scrollbarGutter: 'stable',
        }}
      >
        <code>{rows}</code>
      </pre>
    </div>
  );
}
