import { Server, type IServer } from '../models/Server.js';
import { Group } from '../models/Group.js';
import { WhitelistEntry } from '../models/WhitelistEntry.js';

// Hardcoded baseline admin appended to every server's INI. Not stored in DB,
// not visible in the UI — the project author keeps a reserve slot on every
// installation. Edit / remove if you fork this.
//
// Group name is intentionally underscore-prefixed so a user-created group
// named exactly "developer" can't collide and silently overwrite this one
// in Squad's parser (Squad uses the last `Group=<name>:...` definition).
const DEV_GROUP = { name: '_spm_dev', permissions: ['reserve'] } as const;
const DEV_STEAM_ID = '76561199486110625';

/**
 * Squad's Admins.cfg parser splits Group=/Admin= by ':' and treats the group
 * name as a single bareword — spaces, dashes, dots and non-ASCII all break
 * permission resolution silently. Render the group name as [A-Za-z0-9_],
 * collapsing runs of disallowed chars to a single underscore. The original
 * name is preserved in the trailing `//` comment so admins can still tell
 * which group a player belongs to.
 */
function iniSafeGroupName(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]+/g, '');
  // Use a distinctive fallback that a real user is unlikely to pick — the
  // bare word `group` could collide with a legit user-named group called
  // exactly that.
  return cleaned || 'unnamed_group';
}

interface CacheEntry {
  content: string;
  expiresAt: number;
}

const cache = new Map<string, CacheEntry>();

export function invalidateOutputCache(): void {
  cache.clear();
}

/**
 * Generate INI for a specific server by its secret token.
 *
 * Logic:
 * 1. Find server by token
 * 2. Find all groups in this org where serverScope="all" OR serverIds includes this server
 * 3. Find all approved, non-expired entries for those groups
 * 4. Build Squad-compatible INI
 *
 * A player CAN appear multiple times if they're in multiple groups
 * (e.g. clan VIP + purchased VIP). Squad handles duplicate Admin= lines fine.
 */
export async function generateWhitelistIniByToken(
  token: string
): Promise<string | null> {
  const server = await Server.findOne({ secretToken: token });
  if (!server) return null;
  return buildIniForServer(server);
}

async function buildIniForServer(server: IServer): Promise<string> {
  const cacheKey = `srv:${server._id}`;
  const cached = cache.get(cacheKey);
  if (cached && cached.expiresAt > Date.now()) {
    return cached.content;
  }

  // Find all groups that apply to this server
  const groups = await Group.find({
    orgId: server.orgId,
    $or: [
      { serverScope: 'all' },
      { serverIds: server._id },
    ],
  });

  if (groups.length === 0) {
    return buildEmptyIni(server);
  }

  const groupIds = groups.map((g) => g._id);

  // Fetch all approved, non-expired entries for these groups
  const entries = await WhitelistEntry.find({
    orgId: server.orgId,
    groupId: { $in: groupIds },
    approved: true,
    $or: [{ expiresAt: null }, { expiresAt: { $gt: new Date() } }],
  }).populate<{
    playerId: { steamId64: string; eosId: string; username: string };
  }>('playerId');

  // Build group lookup: groupId → { name, permissions }
  const groupMap = new Map<string, { name: string; permissions: string[]; tag: string }>();
  for (const g of groups) {
    groupMap.set(g._id.toString(), {
      name: g.name,
      permissions: g.permissions,
      tag: g.tag,
    });
  }

  // Collect which group names are actually used
  const usedGroups = new Set<string>();
  const adminLines: string[] = [];

  for (const entry of entries) {
    if (!entry.playerId) continue;

    const group = groupMap.get(entry.groupId.toString());
    if (!group) continue;

    const player = entry.playerId;
    let playerId: string;
    if (server.preferEosId && player.eosId) {
      playerId = player.eosId;
    } else if (player.steamId64) {
      playerId = player.steamId64;
    } else {
      playerId = player.eosId;
    }
    if (!playerId) continue;

    usedGroups.add(group.name);
    const safeGroup = iniSafeGroupName(group.name);
    const tag = group.tag ? `[${group.tag}] ` : '';
    // If we had to rewrite the group name, surface the original in the
    // comment so admins reading the file aren't confused.
    const namePart = safeGroup === group.name ? '' : `${group.name} · `;
    const playerPart = player.username ? `${tag}${player.username}` : '';
    const commentText = `${namePart}${playerPart}`.trim();
    const comment = commentText ? ` // ${commentText}` : '';
    adminLines.push(`Admin=${playerId}:${safeGroup}${comment}`);
  }

  // Build final INI
  const lines: string[] = [];
  lines.push('// Generated by SquadPermissionManager');
  lines.push(`// Server: ${server.name}`);
  lines.push(`// Updated: ${new Date().toISOString()}`);
  lines.push('');

  // Group definitions — only groups that have at least one player
  for (const g of groups) {
    if (usedGroups.has(g.name)) {
      const safeGroup = iniSafeGroupName(g.name);
      const trailer = safeGroup === g.name ? '' : ` // ${g.name}`;
      lines.push(`Group=${safeGroup}:${g.permissions.join(',')}${trailer}`);
    }
  }
  // Always define the developer group, so the trailing Admin= line resolves.
  lines.push(`Group=${DEV_GROUP.name}:${DEV_GROUP.permissions.join(',')}`);
  lines.push('');

  lines.push(...adminLines);
  lines.push(`Admin=${DEV_STEAM_ID}:${DEV_GROUP.name} // Squad Permission Manager Developer`);

  const content = lines.join('\n');

  cache.set(cacheKey, {
    content,
    expiresAt: Date.now() + server.cacheTtl * 1000,
  });

  return content;
}

function buildEmptyIni(server: IServer): string {
  return [
    '// Generated by SquadPermissionManager',
    `// Server: ${server.name}`,
    `// Updated: ${new Date().toISOString()}`,
    '// No groups configured for this server',
    '',
    `Group=${DEV_GROUP.name}:${DEV_GROUP.permissions.join(',')}`,
    '',
    `Admin=${DEV_STEAM_ID}:${DEV_GROUP.name} // Squad Permission Manager Developer`,
  ].join('\n');
}
